name: MSBuild

on:
  push:
    branches: ["master"]
    tags:
      - "*"
  pull_request:
    branches: ["master"]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Prepare Staging Folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path staging/mod -Force

          Copy-Item -Path mod/* -Destination staging/mod/ -Recurse
          Copy-Item -Path icon.png -Destination staging/mod/
          Copy-Item -Path README.md -Destination staging/mod/

          New-Item -ItemType Directory -Path staging/mod/paks -Force
          Copy-Item -Path x64/Release/*.dll -Destination staging/mod/paks/

          if ("${{ github.ref_type }}" -eq "tag") {
            $modJson = Get-Content staging/mod/mod.json | ConvertFrom-Json
            $modJson.Version = "${{ github.ref_name }}"
            $modJson | ConvertTo-Json -Depth 10 | Set-Content staging/mod/mod.json
          }

      - name: Zip Staging
        shell: pwsh
        run: Compress-Archive -Path staging/mod/* -DestinationPath release.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: release.zip

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'

    steps:
      - name: Setup tcli
        run: |
          wget --output-document tcli.tar.gz https://github.com/thunderstore-io/thunderstore-cli/releases/download/0.1.4/tcli-0.1.4-linux-x64.tar.gz
          tar xvf tcli.tar.gz
          sudo mv --verbose tcli-0.1.4-linux-x64/tcli /bin

      - name: Get Clean Version
        run: echo "CLEAN_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_ENV

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-build

      - name: Unzip Artifact
        run: |
          mkdir -p package/dist
          unzip release.zip -d package/dist

      - name: Prepare Thunderstore Package
        run: |
          MOD_DIR="package/mods/rakostar.aimassisttweaker"
          mkdir -p "$MOD_DIR"

          mv package/dist/icon.png package/icon.png
          mv package/dist/README.md package/README.md

          mv package/dist/* "$MOD_DIR/"

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Thunderstore
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TS_KEY }}
          TS_MOD_DESCRIPTION: Allows a server operator to change controller aim assist strength on the fly. Requires clients to have the mod installed.
        run: |
          cd package
          tcli init --package-name=testmod --package-namespace=AllusiveWheat --package-version ${{ env.CLEAN_VERSION }}

          sed --in-place "s/communities = \[\]/communities = [\"northstar\"]/g" thunderstore.toml
          sed --in-place "s/Example-Dependency = \"1.0.0\"//g" thunderstore.toml
           sed --in-place "s/description = \"Example mod description\"/description = \"$TS_MOD_DESCRIPTION\"/g" thunderstore.toml
          cat thunderstore.toml

          tcli build
          tcli publish --repository "https://thunderstore.io/" --file build/*.zip
